# Generated by Django 5.2.9 on 2025-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('BCA VA', 'BCA VA'), ('qris', 'QRIS')], max_length=20),
        ),
    ]
