# Generated by Django 5.2.9 on 2025-12-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='takeaway_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
