# Generated by Django 5.2.9 on 2025-12-31 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_needs_preparation_alter_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafe_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafes',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.cafe'),
        ),
        migrations.AddField(
            model_name='product',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.cafe'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.cafe'),
        ),
        migrations.AddField(
            model_name='user',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.cafe'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('cafe', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('cafe', 'transaction_number')},
        ),
    ]
