# Generated by Django 5.2.9 on 2025-12-31 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20251231_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.cafe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.cafe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.cafe'),
            preserve_default=False,
        ),
    ]
